embed:
  _default:
    color: 0x277baf

  footer:
    string: "LxJDA - Made by L1x"
    icon: "https://footer-icon.png"

  success:
    string: "Action réalisée avec succès !"
    color: 0x277baf
    icon: "https://success-icon.png"

  error:
    string: "Une erreur s'est produite..."
    color: 0x277baf
    icon: "https://error-icon.png"

id:
  0:
    channel:
      log: 0

error:
  command:
    notFound: "La commande est introuvable."
    internal: "Une erreur interne s'est produite."
    adminOnly: "Permissions insuffisantes."

  config:
    reloadFailed: "Le rechargement du fichier de configuration a échoué."
